[[constraint]]
  name = "github.com/aws/aws-lambda-go"
  version = "1.23.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.37.24"

[[constraint]]
  name = "github.com/stretchr/testify/assert"
  version = "1.7.0"


[prune]
  go-tests = true
  unused-packages = true
