
service: devices-api
app: devices-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  environment:
        TABLE_NAME: devices-table-${opt:stage, self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:*:*:*"
#  stage: dev
#  region: us-east-1


package:
  individually: true

functions:
  getDevice:
      handler: bin/getDeviceBin
      package:
        include:
          - ./bin/getDeviceBin
      events:
        - http: 
            path: api/devices/{id}
            method: GET
  createDevice:
    handler: bin/createDeviceBin
    package:
      include:
        - ./bin/createDeviceBin
    events:
      - http: 
          path: api/devices
          method: POST
            
resources:
  Resources:
    DevicesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: 'devices-table-${opt:stage, self:provider.stage}'